language: objective-c
xcode_project: Example/Async.xcodeproj
xcode_scheme: AsyncTests

script: 
  - xctool -project Example/Async.xcodeproj -scheme AsyncTests build test -sdk iphonesimulator  GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
before_install:
  pip install codecov
after_success:
  cd $TRAVIS_BUILD_DIR && codecov
