language: objective-c
xcode_project: Example/Async.xcodeproj
xcode_scheme: AsyncTests

install:
  - bundle install --without=documentation
script: ./test.sh
after_success:
  - cd $TRAVIS_BUILD_DIR && slather

